"""First-class observation-derived boundary objects for Struct3D.

The canonical theory path has exactly one primitive input: a finite observation
X.  This module packages every formerly external mathematical boundary into
objects determined by X and the X-derived Unit universe:

    X -> (A, Gamma, M, G_B, N_X, S_X, C_R, Phi_X).

The package is provenance-bearing and deterministic.  It contains no semantic
labels, learned parameters, caller-selected thresholds, or external theorem
objects.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Iterator, Mapping, Sequence, Tuple

from .theory_candidates import ObservationCandidateFamily
from .theory_core import StructuralUnit
from .theory_energy_model import Observation3D, GeometricModel, WeightedObservationGraph

if TYPE_CHECKING:
    from .theory_observation import ObservationDerivedContext, ObservationRelationCandidateDomain
    from .theory_representation import StructuralRepresentation
    from .theory_stability import StabilityNeighborhood


@dataclass(frozen=True)
class ObservationNeighborhoodFamily:
    """The complete finite N_X family for all X-derived Unit candidates."""

    observation: Observation3D
    units: Tuple[StructuralUnit, ...]
    neighborhoods: Tuple[Tuple[Tuple[int, ...], "StabilityNeighborhood"], ...]

    @classmethod
    def from_context(cls, context: "ObservationDerivedContext") -> "ObservationNeighborhoodFamily":
        from .theory_observation import observation_neighborhood
        units = tuple(context.unit_candidates)
        entries = tuple(
            (tuple(unit.indices), observation_neighborhood(unit, context.observation))
            for unit in units
        )
        return cls(context.observation, units, entries)

    def for_unit(self, unit: StructuralUnit) -> "StabilityNeighborhood":
        key = tuple(unit.indices)
        for candidate_key, neighborhood in self.neighborhoods:
            if candidate_key == key:
                return neighborhood
        raise ValueError("Unit is not an X-derived candidate")

    def __len__(self) -> int:
        return len(self.neighborhoods)

    @property
    def finite(self) -> bool:
        return True


@dataclass(frozen=True)
class ObservationSubcandidateFamily:
    """The complete finite S_X family for all X-derived Unit candidates."""

    observation: Observation3D
    units: Tuple[StructuralUnit, ...]
    subcandidates: Tuple[Tuple[Tuple[int, ...], Tuple[StructuralUnit, ...]], ...]

    @classmethod
    def from_context(cls, context: "ObservationDerivedContext") -> "ObservationSubcandidateFamily":
        from .theory_observation import observation_proper_subcandidates
        units = tuple(context.unit_candidates)
        entries = tuple(
            (tuple(unit.indices), observation_proper_subcandidates(unit, context.observation))
            for unit in units
        )
        return cls(context.observation, units, entries)

    def for_unit(self, unit: StructuralUnit) -> Tuple[StructuralUnit, ...]:
        key = tuple(unit.indices)
        for candidate_key, values in self.subcandidates:
            if candidate_key == key:
                return values
        raise ValueError("Unit is not an X-derived candidate")

    def __len__(self) -> int:
        return len(self.subcandidates)

    @property
    def finite(self) -> bool:
        return True


@dataclass(frozen=True)
class ObservationRepresentationMap:
    """First-class Phi_X map generated by one observation context."""

    context: "ObservationDerivedContext"

    def __call__(self, world) -> "StructuralRepresentation":
        if getattr(world, "observation_context", None) is not self.context:
            raise ValueError("Phi_X requires a World generated by the same observation context")
        from .theory_representation import represent_observation
        return represent_observation(world, self.context)

    @property
    def dimension(self) -> int:
        from .theory_representation_schema import REPRESENTATION_DIM
        return REPRESENTATION_DIM

    def is_quotient_compatible(self) -> bool:
        return self.context is not None


@dataclass(frozen=True)
class ObservationDerivedBoundaries:
    """Single frozen carrier for all X-derived theory boundaries."""

    context: "ObservationDerivedContext"
    candidates: ObservationCandidateFamily
    models: Tuple[GeometricModel, ...]
    boundary_graph: WeightedObservationGraph
    neighborhoods: ObservationNeighborhoodFamily
    subcandidates: ObservationSubcandidateFamily
    units: Tuple[StructuralUnit, ...]
    relation_domain: "ObservationRelationCandidateDomain"
    representation_map: ObservationRepresentationMap

    @classmethod
    def from_context(cls, context: "ObservationDerivedContext") -> "ObservationDerivedBoundaries":
        from .theory_observation import ObservationRelationCandidateDomain
        units = tuple(context.unit_candidates)
        return cls(
            context=context,
            candidates=context.candidates,
            models=tuple(context.model_family),
            boundary_graph=context.boundary_graph,
            neighborhoods=ObservationNeighborhoodFamily.from_context(context),
            subcandidates=ObservationSubcandidateFamily.from_context(context),
            units=units,
            relation_domain=ObservationRelationCandidateDomain.from_observation(context.observation, units),
            representation_map=ObservationRepresentationMap(context),
        )

    @property
    def A(self):
        return self.candidates.a_max

    @property
    def A_max(self):
        return self.candidates.a_max

    @property
    def Gamma(self):
        return self.candidates.gamma

    @property
    def M(self):
        return self.models

    @property
    def G_B(self):
        return self.boundary_graph

    @property
    def N_X(self):
        return self.neighborhoods

    @property
    def S_X(self):
        return self.subcandidates

    @property
    def C_R(self):
        return self.relation_domain

    @property
    def Phi_X(self):
        return self.representation_map

    def neighborhood(self, unit: StructuralUnit):
        return self.neighborhoods.for_unit(unit)

    def proper_subcandidates(self, unit: StructuralUnit) -> Tuple[StructuralUnit, ...]:
        return self.subcandidates.for_unit(unit)

    def restrict_relation_domain(self, units: Sequence[StructuralUnit]):
        """Derive the World-local restriction from the global C_R(X)."""
        from .theory_observation import ObservationRelationCandidateDomain
        normalized = tuple(units)
        return ObservationRelationCandidateDomain.from_observation(self.context.observation, normalized)

    def finite_and_nonempty(self) -> bool:
        return bool(self.A) and bool(self.M) and bool(self.units) and self.C_R.finite

    def quotient_compatible(self) -> bool:
        return (
            self.candidates.is_maximal()
            and self.neighborhoods.finite
            and self.subcandidates.finite
            and self.C_R.finite
            and self.G_B.universe_size == len(self.context.observation.points)
            and self.Phi_X.dimension == 23
        )


__all__ = [
    "ObservationNeighborhoodFamily",
    "ObservationSubcandidateFamily",
    "ObservationRepresentationMap",
    "ObservationDerivedBoundaries",
]
